from tkinter import *
w=Tk()
w.geometry("400x500")
w.title("product entry details")
w.config(bg="pink")
Label(text="productname").grid(row=0,column=0)
productname=Entry()
productname.grid(row=0,column=1)
Label(text="price").grid(row=1,column=0)
price=Entry()
price.grid(row=1,column=1)
Label(text="quantity ").grid(row=2,column=0)
quantity=Entry()
quantity.grid(row=2,column=1)
def enter():
    item=productname.get()
    a=(price.get())
    b=(quantity.get())
    f=open("data.txt","a")
    f.write(item)
    f.write(" ")
    f.write(a)
    f.write(" ")
    f.write(b)
    f.write(" ")
    f.write("\n")
Button(text="enter",command=enter).grid(row=3,column=1,columnspan=2)
w.mainloop()
