product=input("enter the name ")
price=input("enter the price")
quantity=input("enter the quantity")
f=open("data.txt","a")
f.write(product)
f.write(" ")
f.write(price)
f.write(" ")
f.write(quantity)
f.write(" ")
f.write("\n")
print("entered sucessfully")
f.close()